ElectronicParts.WebUI/Models/ElectronicPartViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using ElectronicParts.Domain.Abstract;
using ElectronicParts.Domain.Entities;

namespace ElectronicParts.WebUI.Models
{
    public class ElectronicPartViewModel
    {
        [Display(Name = "Some Items")]   
        public IEnumerable<ElectronicPart> EleParts { get; set; }
        public IElectronicPartRepository ElectronicRepo { get; set; }
    }
}

ElectronicParts.WebUI/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace ElectronicParts.WebUI.Models
{
    public class LoginViewModel
    {   
        [Required(ErrorMessage ="Podaj nazwe uzytkownika.")]
        public string UserName { get; set; }

        [Required(ErrorMessage ="Prosz podaj hasło.")]
        [DataType(DataType.Password)]
        public string Passsword { get; set; }

    }
}

ElectronicParts.WebUI/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ElectronicParts.WebUI.Infrastructure.Abstract;
using ElectronicParts.WebUI.Models;

namespace ElectronicParts.WebUI.Controllers
{
    public class AccountController : Controller
    {
        IAuthProvider authProvider;
        public AccountController(IAuthProvider auth)
        {
            authProvider = auth;
        }

        public ViewResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(LoginViewModel model, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                if (authProvider.Authenticate(model.UserName, model.Passsword))
                {
                    return Redirect(returnUrl ?? Url.Action("Index", "Admin"));
                }
                else
                {
                    ModelState.AddModelError("", "Nieprawidłowa nazwa użytkownika lub nieprawidłowe hasło");
                    return View();
                }
            }
            else
            {
                return View();
            }
        }
    }
}

ElectronicParts.WebUI/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ElectronicParts.Domain.Abstract;
using ElectronicParts.Domain.Entities;

namespace ElectronicParts.WebUI.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        private IElectronicPartRepository ElectronicRepo;

        public AdminController(IElectronicPartRepository repo)
        {
            ElectronicRepo = repo;
        }

        // GET: Admin
        public ViewResult Index()
        {
            return View(ElectronicRepo.ElectronicParts);
        }

        public ViewResult Edit(int ElectronicPartID)
        {
            ElectronicPart part = ElectronicRepo.ElectronicParts
                .FirstOrDefault(p => p.ElectronicPartID == ElectronicPartID);
            return View(part);
        }

        [HttpPost]
        public ActionResult Edit(ElectronicPart electronicPart)
        {

            if (ModelState.IsValid)
            {
                ElectronicRepo.SaveItem(electronicPart);
                TempData["message"] = string.Format("Zapiasano {0}", electronicPart.Category);
                return RedirectToAction("Index");
            }
            else
            {
                return View(electronicPart);
            }
        }

        public ViewResult Create()
        {
            return View("Edit", new ElectronicPart());
        }

        [HttpPost]
        public ActionResult Delete(int ElectronicPartID)
        {
            ElectronicPart deletedItem = ElectronicRepo.DeleteItem(ElectronicPartID);
            if (deletedItem != null)
            {
                TempData["message"] = string.Format("Usunieto {0}", deletedItem.Category);
                return RedirectToAction("Index");
            }
            else
                return View("Index");
            
        }

    }
}

ElectronicParts.WebUI/Controllers/ElectronicPartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ElectronicParts.Domain.Abstract;
using ElectronicParts.Domain.Entities;
using ElectronicParts.WebUI.Models;

namespace ElectronicParts.WebUI.Controllers
{
    public class ElectronicPartController : Controller
    {
        private IElectronicPartRepository repository;
        // GET: Resistor

        public ElectronicPartController(IElectronicPartRepository electrRepo)
        {
            this.repository = electrRepo;
        }


        public ViewResult AkcjaBezWidoku()
        {
            return View();
        }

        public ViewResult List(string category, decimal ? resistance)
        {
            ElectronicPartViewModel model = new ElectronicPartViewModel
            {
                EleParts = repository.ElectronicParts
                .Where(p => category == null || p.Category == category)
                .Where(p => resistance == null || p.Value == resistance),

            };
            return View(model);

        }
    }
}

ElectronicParts.WebUI/Controllers/NavigationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ElectronicParts.Domain.Abstract;


namespace ElectronicParts.WebUI.Controllers
{
    public class NavigationController : Controller
    {
        private IElectronicPartRepository repo;
        public NavigationController(IElectronicPartRepository electroRepo)
        {
            repo = electroRepo;
        }

        // GET: Navigation
        public PartialViewResult Menu(string category = null)
        {
            ViewBag.WybranaKat = category;

            IEnumerable<string> dane = repo.ElectronicParts
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);

            return PartialView(dane);
        }
    }
}

ElectronicParts.WebUI/Views/Admin/Edit.cshtml
@model ElectronicParts.Domain.Entities.ElectronicPart

@*@{
    ViewBag.Title = "Edycja" + Model.Name + "administracyjna";
}*@


<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

<h1> Edycja @*@Model.Category*@ </h1>

@using (Html.BeginForm("Edit", "Admin"))
{

    @Html.HiddenFor(m => m.ElectronicPartID);
<div class="form-group col-sm-3">
    <div class="row">
        <label>Wartość:</label>
        @Html.TextBoxFor(m => m.Value, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Value)
    </div>
    <div class="row">
        <label>Cena:</label>
        @Html.TextBoxFor(m => m.Price, new { @class = "form-control" })
        @Html.ValidationMessageFor(m=>m.Price)
    </div>
    <div class="row">
        <label>Dopuszczalna moc:</label>
        @Html.TextBoxFor(m => m.MaxPower, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.MaxPower)
    </div>
    <div class="row">
        <label>Nazwa:</label>
        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Name)
    </div>
    <div class="row">
        <label>Tolerancja:</label>
        @Html.TextBoxFor(m => m.Tolerance, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Tolerance)
    </div>


    @*@Html.EditorForModel()*@
    <div class="row">
        @if (Model.ElectronicPartID == 0)
        {
            @Html.DropDownListFor(p=>p.Category, new List<SelectListItem>
                   {
                           new SelectListItem { Text="Rezystor",Value="Rezystor"},
                           new SelectListItem { Text="Kondensator",Value="Kondensator"},
                           new SelectListItem { Text="Cewka",Value="Cewka"}

                   },"Wybierz kategorie")
        }
        <button type="submit" class="btn btn-danger">Zapisz</button>
        @Html.ActionLink("Anuluj i powróc do listy", "Index")
    </div>
</div>
}

ElectronicParts.WebUI/Views/Admin/Index.cshtml
@model IEnumerable<ElectronicParts.Domain.Entities.ElectronicPart>

@{
    ViewBag.Title = "Index";
}

<h2>Panel administracyjny</h2>

<p>
    @Html.ActionLink("Stwórz nowy element", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Category)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Value)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MaxPower)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>        
        <th>
            @Html.DisplayNameFor(model => model.Tolerance)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        using (Html.BeginForm("Delete", "Admin", new { item.ElectronicPartID }))
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.Category)</td>
                <td>@Html.DisplayFor(modelItem => item.Value)</td>
                <td>@Html.DisplayFor(modelItem => item.Price)</td>
                <td>@Html.DisplayFor(modelItem => item.MaxPower)</td>
                <td>@Html.DisplayFor(modelItem => item.Name)</td>
                <td>@Html.DisplayFor(modelItem => item.Tolerance)</td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { item.ElectronicPartID }) |
                    <input type="submit" value="Delete" />
                </td>
            </tr>
        }
    }

</table>

ElectronicParts.WebUI/Views/ElectronicPart/List.cshtml
@model ElectronicParts.WebUI.Models.ElectronicPartViewModel

@{
    ViewBag.Title = "Elementy Elektroniczne";

}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

</head>

<body>
    <div class="row">
        <div class="col-md-4">
            @Html.Action("Menu", "Navigation")
            <h6 style="font-weight:bold; font-size:20px;">Podaj wartość elementu</h6>
            @using (Html.BeginForm("List", "ElectronicPart", FormMethod.Get))
            {@Html.TextBox("resistance")
            <input class="btn btn-danger" type="submit" value="Szukaj" />}
        </div>

        <div class="col-md-6">
            <header>
                <h2 class="logo">Baza danych elementów elektronicznych</h2>
            </header>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Kategoria</th>
                        <th>Wartość</th>
                        <th>Cena</th>
                        <th>Maks. moc</th>
                        <th>Typ</th>
                        <th>Tolerancja</th>
                    </tr>
                </thead>

                @foreach (var item in Model.EleParts)
                {
                    string jednostka = "none";
                    if (item.Category == "Rezystor") { jednostka = "kΩ"; }
                    else if (item.Category == "Cewka") { jednostka = "µH"; }
                    else { jednostka = "μF"; }
                    <tr>
                        <td> @Html.DisplayFor(modelItem => item.Category)</td>
                        <td style="width:100px"> @Html.DisplayFor(modelItem => item.Value) @jednostka  </td>
                        <td style="width:100px"> @Html.DisplayFor(modelItem => item.Price) zł</td>
                        <td style="width:100px"> @Html.DisplayFor(modelItem => item.MaxPower) W</td>
                        <td> @Html.DisplayFor(modelItem => item.Name)</td>
                        <td> @Html.DisplayFor(modelItem => item.Tolerance)%</td>
                    </tr>
                }
            </table>
        </div>
    </div>


</body>
</html>

ElectronicParts.WebUI/Views/Navigation/Menu.cshtml
@model IEnumerable<string>


@foreach (var dane in Model)
{
    @Html.RouteLink(dane,new {

    controller = "ElectronicPart",
    action = "List",
    category = dane



}, new { @class = "btn btn-default btn-lg" + (dane == ViewBag.WybranaKat ? "btn btn-primary btn-lg" : "") })
}

ElectronicParts.WebUI/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>

    <link rel="stylesheet" href="~/Content/bootstrap.css" type="text/css" />
</head>
<body>
    <div>      
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }
        @RenderBody()
    </div>
</body>
</html>

ElectronicParts.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>@ViewBag.Title</title>

    <link rel="stylesheet" href="~/Content/ElectronicAppStyle.css" type="text/css" />
    <link rel="stylesheet" href="~/Content/bootstrap.css" type="text/css" />




</head>


<body>
    <main>
        <section class="electronic">
            @if (TempData["message"] != null)
            {
                <div class="alert alert-success">@TempData["message"]</div>
            }
            <header>
                <nav>
                    <div class="menu">
                        <ul>
                            <li>@Html.ActionLink("Baza danych", "List", "ElectronicPart", new { category = string.Empty }, null)</li>
                            <li>@Html.ActionLink("Panel Admina", "Index", "Admin", new { category = string.Empty }, null)</li>
                            <li>@Html.ActionLink("Kontakt", "List", "ElectronicPart", new { category = string.Empty }, null)</li>
                        </ul>
                    </div>

                </nav>
            </header>

            <div class="container">
                @RenderBody()
            </div>



            <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        </section>
    </main>
</body>
</html>